### ISSUE TITLE
Problem during learning OSPF on iosxr/iosxe

### ISSUE THREAD

**Issue by albelozer** [CiscoTestAutomation/genielibs#6]
I can't learn OSPF from XE and XR devices. 100% reproducible. Looks like an error in the model.

I run genie in bash:

```
genie learn "ospf" --testbed-file virl.yaml --devices xe_device --output ospf_xe_device

Learning '['ospf']' on devices '['xe_device']'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.05s/it]
+==============================================================================+
| Genie Learn Summary for device xe_device                             |
+==============================================================================+
|  Connected to xe_device                                              |
|  -   Log: ospf_xe_device/connection_xe_device.txt            |
|------------------------------------------------------------------------------|
|  Could not learn feature 'ospf'                                              |
|  -  Exception:                                                               |
| ospf_xe_device/ospf_iosxe_xe_device_exception.txt            |
|  -  Ops structure:                                                           |
| ospf_xe_device/ospf_iosxe_xe_device_ops.txt                  |
|  -  Device Console:                                                          |
| ospf_xe_device/ospf_iosxe_xe_device_console.txt              |
|==============================================================================|
```

For XE:
```
Issue while building the feature

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 310, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/Users/abelozer/.local/share/virtualenvs/CL-DevNet-2595-HBhBayNK/lib/python3.7/site-packages/genie/libs/ops/ospf/iosxe/ospf.py", line 1006, in learn
    self.make(final_call=True)
  File "src/genie/ops/base/base.py", line 95, in genie.ops.base.base.Base.make
  File "src/genie/ops/base/maker.py", line 272, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 375, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/abelozer/.local/share/virtualenvs/CL-DevNet-2595-HBhBayNK/lib/python3.7/site-packages/genie/libs/parser/iosxe/show_protocols.py", line 935, in cli
    ospf_dict['areas'][area]['configured_interfaces'] = routing_network_intfs
KeyError: 'areas'
```

For XR:

```
Issue while building the feature

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 310, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/Users/abelozer/.local/share/virtualenvs/CL-DevNet-2595-HBhBayNK/lib/python3.7/site-packages/genie/libs/ops/ospf/iosxr/ospf.py", line 960, in learn
    self.make(final_call=True)
  File "src/genie/ops/base/base.py", line 95, in genie.ops.base.base.Base.make
  File "src/genie/ops/base/maker.py", line 272, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 375, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/Users/abelozer/.local/share/virtualenvs/CL-DevNet-2595-HBhBayNK/lib/python3.7/site-packages/genie/libs/parser/iosxr/show_ospf.py", line 924, in cli
    sub_dict['priority'] = int(m.groupdict()['priority'])
UnboundLocalError: local variable 'sub_dict' referenced before assignment
```

**Comment by jeaubin** [comment]
Hi,

Can you send us your device output, the console file at pyats-support-ext@cisco.com

We will fix it up and make sure it works with your output/configuration.

**Comment by jeaubin** [comment]
This has been fixed, will be part of the next release.

**Comment by nujo** [comment]
Hello iI'm still getting the error


Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 330, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/usr/local/lib/python3.6/site-packages/genie/libs/ops/ospf/iosxe/ospf.py", line 1017, in learn
    self.make(final_call=True)
  File "src/genie/ops/base/base.py", line 101, in genie.ops.base.base.Base.make
  File "src/genie/ops/base/maker.py", line 311, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 414, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 271, in genie.metaparser._metaparser.MetaParser.parse
  File "/usr/local/lib/python3.6/site-packages/genie/libs/parser/iosxe/show_ospf.py", line 3546, in cli
    sub_dict['priority'] = int(m.groupdict()['priority'])
UnboundLocalError: local variable 'sub_dict' referenced before assignment


genie.libs.parser VERSION
    19.10

**Comment by thaixuann** [comment]
Hello @nujo,

Thanks for reporting the issue. Could you please send the device output so we can further debug?

Please to pyats-support-ext@cisco.com.

Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by thaixuann** [comment]
Hello @nujo,

Thanks for reporting the issue. Could you please send the device output so we can further debug?

Please to pyats-support-ext@cisco.com.

Thanks,
--Thai.

**Comment by thaixuann** [comment]
Hello @nujo,
Can you please let's know if you are still experiencing this issue? If not, please send the output to pyats-support-ext@cisco.com.
I will proceed to close this issue by December 11. 
Thanks,
--Thai.

**Comment by albelozer** [comment]
Can't confirm now. Please close it.
